"""0002_add_sm2_fields_to_flashcards

Revision ID: 4639651e15a6
Revises: d3e5d264dd3b
Create Date: 2026-06-02 00:34:42.690815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4639651e15a6'
down_revision = 'd3e5d264dd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('repetitions', sa.Integer(), nullable=False))
    op.add_column('flashcards', sa.Column('interval_days', sa.Integer(), nullable=False))
    op.add_column('flashcards', sa.Column('ease_factor', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'ease_factor')
    op.drop_column('flashcards', 'interval_days')
    op.drop_column('flashcards', 'repetitions')
    # ### end Alembic commands ###
