"""0003_add_payments_table

Revision ID: 5ef76075b9b2
Revises: 4639651e15a6
Create Date: 2026-06-02 00:46:46.510805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef76075b9b2'
down_revision = '4639651e15a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
